### ISSUE TITLE
Scrannel sound on Apple Watch

### ISSUE THREAD

**Issue by ozgurshn** [GrantJEmerson/SwiftSynth#2]
I tried to run this oscillator on Series 2 watch but it sounds scrannel but when I tried on simulator in sounds good. What could be the reason, do you have any idea? I'm running oscillator within the range of 100-900 frequency and 0-1 amplitude.

**Comment by GrantJEmerson** [comment]
That's definitely strange. I haven't ever tried to use AVAudioSourceNodes on the Apple Watch so I'm not sure what could be the cause. Maybe your simulator is on a different version of watchOS than your watch.

**Comment by ozgurshn** [comment]
Yes I didn't try on Series 2 simulator but Series 4 and 5. I will download the same simulator with same watchOS and try on that one. Maybe, watch speaker not able to produce this frequency range? This is not a problem of this library but I just wanted to ask.
